import type {
  UsernameDatabaseCategory,
  UsernameDatabaseStyle,
  UsernameLengthBucket,
  UsernameRarity,
} from "@/lib/username-database";

export type UsernameDatabasePageDefinition = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  intro: string;
  keywords: string[];
  categories?: UsernameDatabaseCategory[];
  styles?: UsernameDatabaseStyle[];
  rarities?: UsernameRarity[];
  lengths?: UsernameLengthBucket[];
  featuredLinks: Array<{
    title: string;
    href: string;
    description: string;
  }>;
};

function createPage(definition: UsernameDatabasePageDefinition): UsernameDatabasePageDefinition {
  return definition;
}

export const usernameDatabasePages: UsernameDatabasePageDefinition[] = [
  createPage({
    slug: "gaming-usernames",
    title: "Gaming Usernames Database",
    seoTitle: "Gaming Usernames Database - Gaming Handle and Gamertag Ideas",
    description: "Browse gaming usernames from the NameLaunchpad database with category filters, copy buttons, and gaming-first naming ideas.",
    intro: "This fixed database page narrows the 50,000-name library down to gaming usernames so users can compare broader gamer-handle patterns before moving into specific game generators.",
    keywords: ["gaming usernames", "gamer handles", "gaming database", "gamertag ideas"],
    categories: ["gaming"],
    featuredLinks: [
      { title: "Username Generator", href: "/username-generator", description: "Generate more gaming usernames with style and length filters." },
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Create broader cross-platform gamer tags for console and PC." },
      { title: "Top Generators", href: "/top-generators", description: "Compare the most used generator pages across the site." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Move into rarer gaming handle directions without leaving the database." },
    ],
  }),
  createPage({
    slug: "social-usernames",
    title: "Social Usernames Database",
    seoTitle: "Social Usernames Database - Social Media Handle Ideas",
    description: "Browse social usernames from the NameLaunchpad database with copy buttons, filters, and social-first naming patterns.",
    intro: "This page focuses the username database on social-first handles for profiles, creator accounts, and multi-platform naming research.",
    keywords: ["social usernames", "social media handles", "creator usernames", "username database"],
    categories: ["social"],
    featuredLinks: [
      { title: "Username Generator", href: "/username-generator", description: "Generate more social-ready usernames with style presets." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Browse more creator-focused names inside the database." },
      { title: "TikTok Username Ideas", href: "/tiktok-username-ideas", description: "Jump into TikTok-focused programmatic SEO pages." },
      { title: "Search Generators", href: "/search?q=social", description: "Search related social and creator generator pages." },
    ],
  }),
  createPage({
    slug: "anime-usernames",
    title: "Anime Usernames Database",
    seoTitle: "Anime Usernames Database - Anime Style Username Ideas",
    description: "Browse anime usernames from the NameLaunchpad database with anime style filters, copy buttons, and related anime naming pages.",
    intro: "This fixed database page is built for anime-inspired names that stay readable as real usernames instead of collapsing into random stylized filler.",
    keywords: ["anime usernames", "anime username database", "stylized usernames", "anime handle ideas"],
    categories: ["anime"],
    styles: ["anime"],
    featuredLinks: [
      { title: "Anime Username Generator", href: "/generators/anime-username-generator", description: "Generate more anime usernames with stylized naming patterns." },
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Compare anime directions with broader fantasy naming." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "Move into softer adjacent styles without losing readability." },
      { title: "Anime Username Guide", href: "/anime-username-guide", description: "Open a dedicated SEO page for anime username ideas and examples." },
    ],
  }),
  createPage({
    slug: "rare-usernames",
    title: "Rare Usernames Database",
    seoTitle: "Rare Usernames Database - Rare, Clean, and Premium Username Ideas",
    description: "Browse rare usernames from the NameLaunchpad database with rarity filters, copy buttons, and related rare-name tools.",
    intro: "This page narrows the full username database down to rarer results so users can compare cleaner and more premium-looking name directions without generic noise.",
    keywords: ["rare usernames", "rare username database", "clean usernames", "premium usernames"],
    categories: ["rare"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "OG Username Finder", href: "/og-username-finder", description: "Find shorter rare names with 4 to 5 character bias." },
      { title: "Rare Username Generator", href: "/generators/rare-username-generator", description: "Open the dedicated rare username generator page." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Jump into the highest-rarity filter page." },
      { title: "Rare Gamertags", href: "/rare-gamertags", description: "Open a rare-name SEO page with more examples and links." },
    ],
  }),
  createPage({
    slug: "legendary-usernames",
    title: "Legendary Usernames Database",
    seoTitle: "Legendary Usernames Database - Highest Rarity Username Ideas",
    description: "Browse legendary usernames from the NameLaunchpad database with copy buttons, rarity filters, and related rare-name pages.",
    intro: "This page surfaces the highest-rarity names in the database for users who want the most standout handles first.",
    keywords: ["legendary usernames", "legendary username database", "rare handles", "premium usernames"],
    rarities: ["legendary"],
    featuredLinks: [
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Step back into broader rare-name results." },
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Compare legendary naming with mythic fantasy directions." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare legendary names with shorter premium-looking handles." },
      { title: "Legendary Usernames Guide", href: "/blog/legendary-usernames", description: "Read a long-form article about legendary username ideas." },
    ],
  }),
  createPage({
    slug: "short-usernames",
    title: "Short Usernames Database",
    seoTitle: "Short Usernames Database - Short Username and Gamertag Ideas",
    description: "Browse short usernames from the NameLaunchpad database with copy buttons, short-length filters, and OG-style naming pages.",
    intro: "This page narrows the database down to short usernames for users who care more about compact, cleaner naming than longer descriptive handles.",
    keywords: ["short usernames", "short username database", "short gamertags", "og usernames"],
    categories: ["short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "OG Username Finder", href: "/og-username-finder", description: "Find even cleaner 4 to 5 character names." },
      { title: "Short Gamer Names", href: "/short-gamer-names", description: "Open the short-name SEO page with more examples." },
      { title: "4 Letter Usernames", href: "/4-letter-usernames", description: "Jump into the stricter 4-character listing page." },
      { title: "Short Gamertag Ideas", href: "/short-gamertag-ideas", description: "See programmatic pages focused on short gamertags." },
    ],
  }),
  createPage({
    slug: "cool-usernames",
    title: "Cool Usernames Database",
    seoTitle: "Cool Usernames Database - Cool Gamer Tags and Username Ideas",
    description: "Browse cool usernames from the NameLaunchpad database with cool-style filters, copy buttons, and related generator pages.",
    intro: "This fixed database page focuses on cool usernames that stay flexible across gaming, streaming, and social profiles without drifting into cluttered naming.",
    keywords: ["cool usernames", "cool username database", "cool gamer tags", "clean handles"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Cool Username Generator", href: "/generators/cool-username-generator", description: "Generate more cool usernames with sharper naming patterns." },
      { title: "Cool Usernames for Gamers", href: "/cool-usernames-for-gamers", description: "Open the SEO page with more cool examples and generator links." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Move into broader gaming-focused database results." },
      { title: "Username Ideas", href: "/username-ideas", description: "Browse a large visual gallery of generated username ideas." },
    ],
  }),
  createPage({
    slug: "aesthetic-usernames",
    title: "Aesthetic Usernames Database",
    seoTitle: "Aesthetic Usernames Database - Soft and Stylish Username Ideas",
    description: "Browse aesthetic usernames from the NameLaunchpad database with copy buttons, style filters, and related aesthetic naming pages.",
    intro: "This page narrows the full database into aesthetic-style names for users who want softer and more visual handles across social and creator contexts.",
    keywords: ["aesthetic usernames", "aesthetic username database", "soft handles", "stylish usernames"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish username ideas." },
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "Move into the softer cute-name side of the database." },
      { title: "Aesthetic Username Ideas", href: "/aesthetic-username-ideas", description: "Open the programmatic SEO page for more aesthetic naming ideas." },
      { title: "Username Ideas for Girls", href: "/blog/username-ideas-for-girls", description: "Read a related long-form article with examples." },
    ],
  }),
  createPage({
    slug: "dark-usernames",
    title: "Dark Usernames Database",
    seoTitle: "Dark Usernames Database - Dark and Edgy Username Ideas",
    description: "Browse dark usernames from the NameLaunchpad database with copy buttons, style filters, and related dark-name pages.",
    intro: "This page narrows the database into darker naming patterns built around shadow, void, crypt, and more ominous visual tone.",
    keywords: ["dark usernames", "dark username database", "edgy usernames", "shadow names"],
    styles: ["dark"],
    categories: ["edgy"],
    featuredLinks: [
      { title: "Dark Username Generator", href: "/generators/dark-username-generator", description: "Generate more dark and edgy usernames." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Move into rarer dark-adjacent names without losing tone." },
      { title: "Dark Usernames Article", href: "/blog/dark-usernames", description: "Read the related long-form dark username guide." },
      { title: "Demon Name Guide", href: "/demon-name-guide", description: "Open a darker fantasy SEO page for adjacent naming ideas." },
    ],
  }),
  createPage({
    slug: "fantasy-usernames",
    title: "Fantasy Usernames Database",
    seoTitle: "Fantasy Usernames Database - RPG and Fantasy Username Ideas",
    description: "Browse fantasy usernames from the NameLaunchpad database with copy buttons, fantasy filters, and related RPG naming pages.",
    intro: "This fixed database page helps RPG players and fantasy fans compare mythic, magical, and heroic usernames without leaving the main database system.",
    keywords: ["fantasy usernames", "fantasy username database", "rpg usernames", "mythic names"],
    styles: ["fantasy"],
    categories: ["fantasy"],
    featuredLinks: [
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Generate more RPG and fantasy-style names directly." },
      { title: "Dragon Name Ideas", href: "/dragon-name-ideas", description: "Open a dragon-focused fantasy SEO page." },
      { title: "Elf Name Guide", href: "/elf-name-guide", description: "See a softer fantasy naming page with elf-style ideas." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Compare mythic fantasy names with the highest-rarity usernames." },
    ],
  }),
  createPage({
    slug: "streamer-usernames",
    title: "Streamer Usernames Database",
    seoTitle: "Streamer Usernames Database - Twitch, YouTube, and Creator Name Ideas",
    description: "Browse streamer usernames from the NameLaunchpad database with copy buttons, creator filters, and related streamer naming pages.",
    intro: "This page narrows the database into streamer-style usernames for users who care about overlays, channel names, clip titles, and creator branding.",
    keywords: ["streamer usernames", "creator usernames", "twitch handles", "youtube gaming names"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "Streamer Name Generator", href: "/generators/streamer-name-generator", description: "Generate more creator-friendly names and live handles." },
      { title: "Twitch Streamer Name Ideas", href: "/twitch-streamer-name-ideas", description: "Open a Twitch-focused programmatic SEO page." },
      { title: "YouTube Gaming Name Guide", href: "/youtube-gaming-name-guide", description: "See a creator-first SEO page for channel branding." },
      { title: "Top Generators", href: "/top-generators", description: "Compare the most used naming tools across the site." },
    ],
  }),
  createPage({
    slug: "cute-usernames",
    title: "Cute Usernames Database",
    seoTitle: "Cute Usernames Database - Cute, Soft, and Friendly Username Ideas",
    description: "Browse cute usernames from the NameLaunchpad database with copy buttons, soft-style filters, and related cute naming pages.",
    intro: "This page narrows the username database into cute and softer handles for users who want more friendly and visually lighter naming patterns.",
    keywords: ["cute usernames", "cute username database", "soft usernames", "friendly handles"],
    categories: ["cute"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and cute-adjacent names." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "Move into broader aesthetic name ideas." },
      { title: "Cool Roblox Usernames", href: "/blog/cool-roblox-usernames", description: "Read a related article with softer and playful naming examples." },
      { title: "Cute Usernames Article", href: "/blog/cute-usernames", description: "Open the dedicated article for cute username ideas." },
    ],
  }),
  createPage({
    slug: "anime-short-usernames",
    title: "Anime Short Usernames Database",
    seoTitle: "Anime Short Usernames Database - Short Anime Username Ideas",
    description: "Browse short anime usernames from the NameLaunchpad database with copy buttons, short-length filters, and related anime naming pages.",
    intro: "This page combines anime styling with shorter length intent for users who want cleaner anime-inspired handles that still feel usable as real usernames.",
    keywords: ["anime short usernames", "short anime usernames", "anime handle ideas", "anime database"],
    categories: ["anime", "short"],
    styles: ["anime"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Anime Usernames", href: "/username-database/anime-usernames", description: "Move into the broader anime username database page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare anime short names with general compact handles." },
      { title: "Anime Username Generator", href: "/generators/anime-username-generator", description: "Generate more anime usernames with stylized naming patterns." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare short anime-style names with cleaner OG-like handles." },
    ],
  }),
  createPage({
    slug: "rare-gaming-usernames",
    title: "Rare Gaming Usernames Database",
    seoTitle: "Rare Gaming Usernames Database - Rare Gamer Handle Ideas",
    description: "Browse rare gaming usernames from the NameLaunchpad database with copy buttons, rarity filters, and gaming-focused handle ideas.",
    intro: "This page narrows the database into rare gaming usernames for users who want names that feel more premium without losing gaming relevance.",
    keywords: ["rare gaming usernames", "rare gamer tags", "gaming database", "premium gaming handles"],
    categories: ["gaming", "rare"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Browse broader gaming database results." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "See more rare usernames outside the gaming-only filter." },
      { title: "Rare Username Generator", href: "/generators/rare-username-generator", description: "Generate more rare username directions directly." },
      { title: "Rare Gamertags", href: "/rare-gamertags", description: "Open the rare gamertag SEO page with more examples and tips." },
    ],
  }),
  createPage({
    slug: "streamer-short-usernames",
    title: "Streamer Short Usernames Database",
    seoTitle: "Streamer Short Usernames Database - Short Creator and Streamer Names",
    description: "Browse short streamer usernames from the NameLaunchpad database with copy buttons, creator filters, and compact branding ideas.",
    intro: "This page is built for users who want streamer-style names but care about shorter and more brandable handles for overlays, clips, and social discovery.",
    keywords: ["short streamer usernames", "creator usernames", "twitch handles", "streamer database"],
    styles: ["streamer"],
    categories: ["social", "short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Open the broader streamer username database page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare creator-focused short names with general compact handles." },
      { title: "Streamer Name Generator", href: "/generators/streamer-name-generator", description: "Generate more streamer and creator names directly." },
      { title: "Twitch Streamer Name Guide", href: "/twitch-streamer-name-guide", description: "Read a related SEO page focused on Twitch naming." },
    ],
  }),
  createPage({
    slug: "aesthetic-cute-usernames",
    title: "Aesthetic Cute Usernames Database",
    seoTitle: "Aesthetic Cute Usernames Database - Soft and Cute Username Ideas",
    description: "Browse aesthetic cute usernames from the NameLaunchpad database with copy buttons, soft-style filters, and related aesthetic naming pages.",
    intro: "This page combines aesthetic and cute naming intent for users who want softer handles with more visual polish and a cleaner profile fit.",
    keywords: ["aesthetic cute usernames", "soft usernames", "cute aesthetic handles", "username database"],
    categories: ["cute"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "Open the broader cute username database page." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "See the wider aesthetic naming page." },
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish username ideas." },
      { title: "Username Ideas for Girls", href: "/blog/username-ideas-for-girls", description: "Read a related article with softer naming examples." },
    ],
  }),
  createPage({
    slug: "dark-rare-usernames",
    title: "Dark Rare Usernames Database",
    seoTitle: "Dark Rare Usernames Database - Rare Dark Username Ideas",
    description: "Browse dark rare usernames from the NameLaunchpad database with copy buttons, rarity filters, and darker naming pages.",
    intro: "This page narrows the database into darker rare usernames for users who want edgier handles with stronger premium feel.",
    keywords: ["dark rare usernames", "rare dark usernames", "edgy rare handles", "dark username database"],
    categories: ["edgy", "rare"],
    styles: ["dark"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "Dark Usernames", href: "/username-database/dark-usernames", description: "Browse broader dark username database results." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Compare with wider rare-name results." },
      { title: "Dark Username Generator", href: "/generators/dark-username-generator", description: "Generate darker names directly." },
      { title: "Dark Usernames Article", href: "/blog/dark-usernames", description: "Read the related long-form dark username guide." },
    ],
  }),
  createPage({
    slug: "fantasy-legendary-usernames",
    title: "Fantasy Legendary Usernames Database",
    seoTitle: "Fantasy Legendary Usernames Database - Legendary Fantasy Username Ideas",
    description: "Browse legendary fantasy usernames from the NameLaunchpad database with copy buttons, rarity filters, and related fantasy naming pages.",
    intro: "This page focuses on the highest-rarity fantasy usernames for users who want mythic, heroic, and more premium-looking handles.",
    keywords: ["fantasy legendary usernames", "legendary fantasy handles", "mythic usernames", "fantasy database"],
    categories: ["fantasy"],
    styles: ["fantasy"],
    rarities: ["legendary"],
    featuredLinks: [
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Browse broader fantasy usernames from the database." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Compare fantasy legendary names with general legendary results." },
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Generate more fantasy names directly." },
      { title: "Dragon Name Guide", href: "/dragon-name-guide", description: "Open a fantasy SEO page with more mythic naming directions." },
    ],
  }),
  createPage({
    slug: "hacker-short-usernames",
    title: "Hacker Short Usernames Database",
    seoTitle: "Hacker Short Usernames Database - Short Tech and Glitch Username Ideas",
    description: "Browse short hacker usernames from the NameLaunchpad database with copy buttons, tech-style filters, and compact handle ideas.",
    intro: "This page combines hacker-style naming with short-length intent for users who want compact techy handles that still stay readable.",
    keywords: ["short hacker usernames", "tech usernames", "glitch handles", "hacker database"],
    styles: ["hacker"],
    categories: ["short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Hacker Usernames", href: "/hacker-usernames", description: "Browse the broader hacker username listing page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare with more general short username results." },
      { title: "Hacker Username Generator", href: "/generators/hacker-username-generator", description: "Generate more tech-heavy usernames directly." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare compact hacker names with cleaner short-name results." },
    ],
  }),
  createPage({
    slug: "gaming-cool-usernames",
    title: "Gaming Cool Usernames Database",
    seoTitle: "Gaming Cool Usernames Database - Cool Gamer Handle Ideas",
    description: "Browse cool gaming usernames from the NameLaunchpad database with copy buttons, gaming filters, and cool handle ideas.",
    intro: "This page narrows the database into cool gaming usernames for users who want flexible gamer handles without drifting into social-only styles.",
    keywords: ["cool gaming usernames", "cool gamer tags", "gaming handle ideas", "gaming database"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Open the broader gaming username database page." },
      { title: "Cool Usernames", href: "/username-database/cool-usernames", description: "Compare with general cool username results." },
      { title: "Cool Username Generator", href: "/generators/cool-username-generator", description: "Generate more cool handle ideas directly." },
      { title: "Cool Usernames for Gamers", href: "/cool-usernames-for-gamers", description: "Read the related SEO page with examples and links." },
    ],
  }),
  createPage({
    slug: "social-aesthetic-usernames",
    title: "Social Aesthetic Usernames Database",
    seoTitle: "Social Aesthetic Usernames Database - Aesthetic Social Handle Ideas",
    description: "Browse aesthetic social usernames from the NameLaunchpad database with copy buttons, style filters, and creator-focused naming pages.",
    intro: "This page narrows the database into aesthetic social usernames for users who care more about profile feel, creator polish, and visual branding.",
    keywords: ["aesthetic social usernames", "social handles", "creator usernames", "aesthetic database"],
    categories: ["social"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Social Usernames", href: "/username-database/social-usernames", description: "Open the broader social username page." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "See the wider aesthetic database page." },
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish handles." },
      { title: "TikTok Username Ideas", href: "/tiktok-username-ideas", description: "Open a related social SEO page." },
    ],
  }),
  createPage({
    slug: "duo-gaming-usernames",
    title: "Duo Gaming Usernames Database",
    seoTitle: "Duo Gaming Usernames Database - Duo Gamer Name Ideas",
    description: "Browse duo gaming usernames from the NameLaunchpad database with copy buttons, duo filters, and related team naming pages.",
    intro: "This page narrows the username database into duo gaming names for users who want paired identities without jumping all the way to clan naming.",
    keywords: ["duo gaming usernames", "duo gamer tags", "pair usernames", "gaming duo names"],
    categories: ["duo", "gaming"],
    featuredLinks: [
      { title: "Duo Usernames", href: "/username-database/duo-usernames", description: "Open the broader duo username database page." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "See more general gaming name directions." },
      { title: "Duo Gamertag Guide", href: "/duo-gamertag-guide", description: "Open a duo-focused SEO page with more examples." },
      { title: "Clan Name Generator", href: "/clan-name-generator", description: "Move into larger team naming when needed." },
    ],
  }),
  createPage({
    slug: "clan-gaming-usernames",
    title: "Clan Gaming Usernames Database",
    seoTitle: "Clan Gaming Usernames Database - Clan and Team Username Ideas",
    description: "Browse clan gaming usernames from the NameLaunchpad database with copy buttons, team filters, and related clan naming pages.",
    intro: "This page narrows the database into clan-oriented gaming usernames for users who need team-ready names instead of solo handles.",
    keywords: ["clan gaming usernames", "team usernames", "clan handles", "gaming clan names"],
    categories: ["clan", "gaming"],
    featuredLinks: [
      { title: "Clan Usernames", href: "/username-database/clan-usernames", description: "Open the broader clan username database page." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Compare with solo gaming handle directions." },
      { title: "Clan Name Generator", href: "/clan-name-generator", description: "Generate more clan and team names directly." },
      { title: "Clan Name Ideas", href: "/blog/clan-name-ideas", description: "Read the related clan naming article." },
    ],
  }),
  createPage({
    slug: "rare-short-usernames",
    title: "Rare Short Usernames Database",
    seoTitle: "Rare Short Usernames Database - Rare Short Username Ideas",
    description: "Browse rare short usernames from the NameLaunchpad database with copy buttons, compact filters, and related rare-name pages.",
    intro: "This page combines short-length and rarity intent for users who want cleaner premium handles that stay compact and memorable.",
    keywords: ["rare short usernames", "short rare handles", "compact rare usernames", "short username database"],
    categories: ["short", "rare"],
    rarities: ["rare", "epic", "legendary"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Open the broader short-name database page." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Compare with wider rare-name results." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Generate or browse very compact premium handles." },
      { title: "Short Gamer Names", href: "/short-gamer-names", description: "Open the short-name SEO page with more examples." },
    ],
  }),
];

export const usernameDatabasePageSlugs = usernameDatabasePages.map((page) => page.slug);

export function getUsernameDatabasePage(slug: string) {
  return usernameDatabasePages.find((page) => page.slug === slug);
}
