import type {
  UsernameDatabaseCategory,
  UsernameDatabaseStyle,
  UsernameLengthBucket,
  UsernameRarity,
} from "@/lib/username-database";

export type UsernameDatabasePageDefinition = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  intro: string;
  keywords: string[];
  categories?: UsernameDatabaseCategory[];
  styles?: UsernameDatabaseStyle[];
  rarities?: UsernameRarity[];
  lengths?: UsernameLengthBucket[];
  featuredLinks: Array<{
    title: string;
    href: string;
    description: string;
  }>;
};

function createPage(definition: UsernameDatabasePageDefinition): UsernameDatabasePageDefinition {
  return definition;
}

export const usernameDatabasePages: UsernameDatabasePageDefinition[] = [
  createPage({
    slug: "gaming-usernames",
    title: "Gaming Usernames Database",
    seoTitle: "Gaming Usernames Database - Gaming Handle and Gamertag Ideas",
    description: "Browse gaming usernames from the NameLaunchpad database with category filters, copy buttons, and gaming-first naming ideas.",
    intro: "This fixed database page narrows the 50,000-name library down to gaming usernames so users can compare broader gamer-handle patterns before moving into specific game generators.",
    keywords: ["gaming usernames", "gamer handles", "gaming database", "gamertag ideas"],
    categories: ["gaming"],
    featuredLinks: [
      { title: "Username Generator", href: "/username-generator", description: "Generate more gaming usernames with style and length filters." },
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Create broader cross-platform gamer tags for console and PC." },
      { title: "Top Generators", href: "/top-generators", description: "Compare the most used generator pages across the site." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Move into rarer gaming handle directions without leaving the database." },
    ],
  }),
  createPage({
    slug: "social-usernames",
    title: "Social Usernames Database",
    seoTitle: "Social Usernames Database - Social Media Handle Ideas",
    description: "Browse social usernames from the NameLaunchpad database with copy buttons, filters, and social-first naming patterns.",
    intro: "This page focuses the username database on social-first handles for profiles, creator accounts, and multi-platform naming research.",
    keywords: ["social usernames", "social media handles", "creator usernames", "username database"],
    categories: ["social"],
    featuredLinks: [
      { title: "Username Generator", href: "/username-generator", description: "Generate more social-ready usernames with style presets." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Browse more creator-focused names inside the database." },
      { title: "TikTok Username Ideas", href: "/tiktok-username-ideas", description: "Jump into TikTok-focused programmatic SEO pages." },
      { title: "Search Generators", href: "/search?q=social", description: "Search related social and creator generator pages." },
    ],
  }),
  createPage({
    slug: "anime-usernames",
    title: "Anime Usernames Database",
    seoTitle: "Anime Usernames Database - Anime Style Username Ideas",
    description: "Browse anime usernames from the NameLaunchpad database with anime style filters, copy buttons, and related anime naming pages.",
    intro: "This fixed database page is built for anime-inspired names that stay readable as real usernames instead of collapsing into random stylized filler.",
    keywords: ["anime usernames", "anime username database", "stylized usernames", "anime handle ideas"],
    categories: ["anime"],
    styles: ["anime"],
    featuredLinks: [
      { title: "Anime Username Generator", href: "/generators/anime-username-generator", description: "Generate more anime usernames with stylized naming patterns." },
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Compare anime directions with broader fantasy naming." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "Move into softer adjacent styles without losing readability." },
      { title: "Anime Username Guide", href: "/anime-username-guide", description: "Open a dedicated SEO page for anime username ideas and examples." },
    ],
  }),
  createPage({
    slug: "rare-usernames",
    title: "Rare Usernames Database",
    seoTitle: "Rare Usernames Database - Rare, Clean, and Premium Username Ideas",
    description: "Browse rare usernames from the NameLaunchpad database with rarity filters, copy buttons, and related rare-name tools.",
    intro: "This page narrows the full username database down to rarer results so users can compare cleaner and more premium-looking name directions without generic noise.",
    keywords: ["rare usernames", "rare username database", "clean usernames", "premium usernames"],
    categories: ["rare"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "OG Username Finder", href: "/og-username-finder", description: "Find shorter rare names with 4 to 5 character bias." },
      { title: "Rare Username Generator", href: "/generators/rare-username-generator", description: "Open the dedicated rare username generator page." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Jump into the highest-rarity filter page." },
      { title: "Rare Gamertags", href: "/rare-gamertags", description: "Open a rare-name SEO page with more examples and links." },
    ],
  }),
  createPage({
    slug: "legendary-usernames",
    title: "Legendary Usernames Database",
    seoTitle: "Legendary Usernames Database - Highest Rarity Username Ideas",
    description: "Browse legendary usernames from the NameLaunchpad database with copy buttons, rarity filters, and related rare-name pages.",
    intro: "This page surfaces the highest-rarity names in the database for users who want the most standout handles first.",
    keywords: ["legendary usernames", "legendary username database", "rare handles", "premium usernames"],
    rarities: ["legendary"],
    featuredLinks: [
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Step back into broader rare-name results." },
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Compare legendary naming with mythic fantasy directions." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare legendary names with shorter premium-looking handles." },
      { title: "Legendary Usernames Guide", href: "/blog/legendary-usernames", description: "Read a long-form article about legendary username ideas." },
    ],
  }),
  createPage({
    slug: "short-usernames",
    title: "Short Usernames Database",
    seoTitle: "Short Usernames Database - Short Username and Gamertag Ideas",
    description: "Browse short usernames from the NameLaunchpad database with copy buttons, short-length filters, and OG-style naming pages.",
    intro: "This page narrows the database down to short usernames for users who care more about compact, cleaner naming than longer descriptive handles.",
    keywords: ["short usernames", "short username database", "short gamertags", "og usernames"],
    categories: ["short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "OG Username Finder", href: "/og-username-finder", description: "Find even cleaner 4 to 5 character names." },
      { title: "Short Gamer Names", href: "/short-gamer-names", description: "Open the short-name SEO page with more examples." },
      { title: "4 Letter Usernames", href: "/4-letter-usernames", description: "Jump into the stricter 4-character listing page." },
      { title: "Short Gamertag Ideas", href: "/short-gamertag-ideas", description: "See programmatic pages focused on short gamertags." },
    ],
  }),
  createPage({
    slug: "cool-usernames",
    title: "Cool Usernames Database",
    seoTitle: "Cool Usernames Database - Cool Gamer Tags and Username Ideas",
    description: "Browse cool usernames from the NameLaunchpad database with cool-style filters, copy buttons, and related generator pages.",
    intro: "This fixed database page focuses on cool usernames that stay flexible across gaming, streaming, and social profiles without drifting into cluttered naming.",
    keywords: ["cool usernames", "cool username database", "cool gamer tags", "clean handles"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Cool Username Generator", href: "/generators/cool-username-generator", description: "Generate more cool usernames with sharper naming patterns." },
      { title: "Cool Usernames for Gamers", href: "/cool-usernames-for-gamers", description: "Open the SEO page with more cool examples and generator links." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Move into broader gaming-focused database results." },
      { title: "Username Ideas", href: "/username-ideas", description: "Browse a large visual gallery of generated username ideas." },
    ],
  }),
  createPage({
    slug: "aesthetic-usernames",
    title: "Aesthetic Usernames Database",
    seoTitle: "Aesthetic Usernames Database - Soft and Stylish Username Ideas",
    description: "Browse aesthetic usernames from the NameLaunchpad database with copy buttons, style filters, and related aesthetic naming pages.",
    intro: "This page narrows the full database into aesthetic-style names for users who want softer and more visual handles across social and creator contexts.",
    keywords: ["aesthetic usernames", "aesthetic username database", "soft handles", "stylish usernames"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish username ideas." },
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "Move into the softer cute-name side of the database." },
      { title: "Aesthetic Username Ideas", href: "/aesthetic-username-ideas", description: "Open the programmatic SEO page for more aesthetic naming ideas." },
      { title: "Username Ideas for Girls", href: "/blog/username-ideas-for-girls", description: "Read a related long-form article with examples." },
    ],
  }),
  createPage({
    slug: "dark-usernames",
    title: "Dark Usernames Database",
    seoTitle: "Dark Usernames Database - Dark and Edgy Username Ideas",
    description: "Browse dark usernames from the NameLaunchpad database with copy buttons, style filters, and related dark-name pages.",
    intro: "This page narrows the database into darker naming patterns built around shadow, void, crypt, and more ominous visual tone.",
    keywords: ["dark usernames", "dark username database", "edgy usernames", "shadow names"],
    styles: ["dark"],
    categories: ["edgy"],
    featuredLinks: [
      { title: "Dark Username Generator", href: "/generators/dark-username-generator", description: "Generate more dark and edgy usernames." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Move into rarer dark-adjacent names without losing tone." },
      { title: "Dark Usernames Article", href: "/blog/dark-usernames", description: "Read the related long-form dark username guide." },
      { title: "Demon Name Guide", href: "/demon-name-guide", description: "Open a darker fantasy SEO page for adjacent naming ideas." },
    ],
  }),
  createPage({
    slug: "fantasy-usernames",
    title: "Fantasy Usernames Database",
    seoTitle: "Fantasy Usernames Database - RPG and Fantasy Username Ideas",
    description: "Browse fantasy usernames from the NameLaunchpad database with copy buttons, fantasy filters, and related RPG naming pages.",
    intro: "This fixed database page helps RPG players and fantasy fans compare mythic, magical, and heroic usernames without leaving the main database system.",
    keywords: ["fantasy usernames", "fantasy username database", "rpg usernames", "mythic names"],
    styles: ["fantasy"],
    categories: ["fantasy"],
    featuredLinks: [
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Generate more RPG and fantasy-style names directly." },
      { title: "Dragon Name Ideas", href: "/dragon-name-ideas", description: "Open a dragon-focused fantasy SEO page." },
      { title: "Elf Name Guide", href: "/elf-name-guide", description: "See a softer fantasy naming page with elf-style ideas." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Compare mythic fantasy names with the highest-rarity usernames." },
    ],
  }),
  createPage({
    slug: "streamer-usernames",
    title: "Streamer Usernames Database",
    seoTitle: "Streamer Usernames Database - Twitch, YouTube, and Creator Name Ideas",
    description: "Browse streamer usernames from the NameLaunchpad database with copy buttons, creator filters, and related streamer naming pages.",
    intro: "This page narrows the database into streamer-style usernames for users who care about overlays, channel names, clip titles, and creator branding.",
    keywords: ["streamer usernames", "creator usernames", "twitch handles", "youtube gaming names"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "Streamer Name Generator", href: "/generators/streamer-name-generator", description: "Generate more creator-friendly names and live handles." },
      { title: "Twitch Streamer Name Ideas", href: "/twitch-streamer-name-ideas", description: "Open a Twitch-focused programmatic SEO page." },
      { title: "YouTube Gaming Name Guide", href: "/youtube-gaming-name-guide", description: "See a creator-first SEO page for channel branding." },
      { title: "Top Generators", href: "/top-generators", description: "Compare the most used naming tools across the site." },
    ],
  }),
  createPage({
    slug: "cute-usernames",
    title: "Cute Usernames Database",
    seoTitle: "Cute Usernames Database - Cute, Soft, and Friendly Username Ideas",
    description: "Browse cute usernames from the NameLaunchpad database with copy buttons, soft-style filters, and related cute naming pages.",
    intro: "This page narrows the username database into cute and softer handles for users who want more friendly and visually lighter naming patterns.",
    keywords: ["cute usernames", "cute username database", "soft usernames", "friendly handles"],
    categories: ["cute"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and cute-adjacent names." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "Move into broader aesthetic name ideas." },
      { title: "Cool Roblox Usernames", href: "/blog/cool-roblox-usernames", description: "Read a related article with softer and playful naming examples." },
      { title: "Cute Usernames Article", href: "/blog/cute-usernames", description: "Open the dedicated article for cute username ideas." },
    ],
  }),
  createPage({
    slug: "anime-short-usernames",
    title: "Anime Short Usernames Database",
    seoTitle: "Anime Short Usernames Database - Short Anime Username Ideas",
    description: "Browse short anime usernames from the NameLaunchpad database with copy buttons, short-length filters, and related anime naming pages.",
    intro: "This page combines anime styling with shorter length intent for users who want cleaner anime-inspired handles that still feel usable as real usernames.",
    keywords: ["anime short usernames", "short anime usernames", "anime handle ideas", "anime database"],
    categories: ["anime", "short"],
    styles: ["anime"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Anime Usernames", href: "/username-database/anime-usernames", description: "Move into the broader anime username database page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare anime short names with general compact handles." },
      { title: "Anime Username Generator", href: "/generators/anime-username-generator", description: "Generate more anime usernames with stylized naming patterns." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare short anime-style names with cleaner OG-like handles." },
    ],
  }),
  createPage({
    slug: "rare-gaming-usernames",
    title: "Rare Gaming Usernames Database",
    seoTitle: "Rare Gaming Usernames Database - Rare Gamer Handle Ideas",
    description: "Browse rare gaming usernames from the NameLaunchpad database with copy buttons, rarity filters, and gaming-focused handle ideas.",
    intro: "This page narrows the database into rare gaming usernames for users who want names that feel more premium without losing gaming relevance.",
    keywords: ["rare gaming usernames", "rare gamer tags", "gaming database", "premium gaming handles"],
    categories: ["gaming", "rare"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Browse broader gaming database results." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "See more rare usernames outside the gaming-only filter." },
      { title: "Rare Username Generator", href: "/generators/rare-username-generator", description: "Generate more rare username directions directly." },
      { title: "Rare Gamertags", href: "/rare-gamertags", description: "Open the rare gamertag SEO page with more examples and tips." },
    ],
  }),
  createPage({
    slug: "streamer-short-usernames",
    title: "Streamer Short Usernames Database",
    seoTitle: "Streamer Short Usernames Database - Short Creator and Streamer Names",
    description: "Browse short streamer usernames from the NameLaunchpad database with copy buttons, creator filters, and compact branding ideas.",
    intro: "This page is built for users who want streamer-style names but care about shorter and more brandable handles for overlays, clips, and social discovery.",
    keywords: ["short streamer usernames", "creator usernames", "twitch handles", "streamer database"],
    styles: ["streamer"],
    categories: ["social", "short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Open the broader streamer username database page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare creator-focused short names with general compact handles." },
      { title: "Streamer Name Generator", href: "/generators/streamer-name-generator", description: "Generate more streamer and creator names directly." },
      { title: "Twitch Streamer Name Guide", href: "/twitch-streamer-name-guide", description: "Read a related SEO page focused on Twitch naming." },
    ],
  }),
  createPage({
    slug: "aesthetic-cute-usernames",
    title: "Aesthetic Cute Usernames Database",
    seoTitle: "Aesthetic Cute Usernames Database - Soft and Cute Username Ideas",
    description: "Browse aesthetic cute usernames from the NameLaunchpad database with copy buttons, soft-style filters, and related aesthetic naming pages.",
    intro: "This page combines aesthetic and cute naming intent for users who want softer handles with more visual polish and a cleaner profile fit.",
    keywords: ["aesthetic cute usernames", "soft usernames", "cute aesthetic handles", "username database"],
    categories: ["cute"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "Open the broader cute username database page." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "See the wider aesthetic naming page." },
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish username ideas." },
      { title: "Username Ideas for Girls", href: "/blog/username-ideas-for-girls", description: "Read a related article with softer naming examples." },
    ],
  }),
  createPage({
    slug: "dark-rare-usernames",
    title: "Dark Rare Usernames Database",
    seoTitle: "Dark Rare Usernames Database - Rare Dark Username Ideas",
    description: "Browse dark rare usernames from the NameLaunchpad database with copy buttons, rarity filters, and darker naming pages.",
    intro: "This page narrows the database into darker rare usernames for users who want edgier handles with stronger premium feel.",
    keywords: ["dark rare usernames", "rare dark usernames", "edgy rare handles", "dark username database"],
    categories: ["edgy", "rare"],
    styles: ["dark"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "Dark Usernames", href: "/username-database/dark-usernames", description: "Browse broader dark username database results." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Compare with wider rare-name results." },
      { title: "Dark Username Generator", href: "/generators/dark-username-generator", description: "Generate darker names directly." },
      { title: "Dark Usernames Article", href: "/blog/dark-usernames", description: "Read the related long-form dark username guide." },
    ],
  }),
  createPage({
    slug: "fantasy-legendary-usernames",
    title: "Fantasy Legendary Usernames Database",
    seoTitle: "Fantasy Legendary Usernames Database - Legendary Fantasy Username Ideas",
    description: "Browse legendary fantasy usernames from the NameLaunchpad database with copy buttons, rarity filters, and related fantasy naming pages.",
    intro: "This page focuses on the highest-rarity fantasy usernames for users who want mythic, heroic, and more premium-looking handles.",
    keywords: ["fantasy legendary usernames", "legendary fantasy handles", "mythic usernames", "fantasy database"],
    categories: ["fantasy"],
    styles: ["fantasy"],
    rarities: ["legendary"],
    featuredLinks: [
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Browse broader fantasy usernames from the database." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Compare fantasy legendary names with general legendary results." },
      { title: "Fantasy Name Generator", href: "/fantasy-name-generator", description: "Generate more fantasy names directly." },
      { title: "Dragon Name Guide", href: "/dragon-name-guide", description: "Open a fantasy SEO page with more mythic naming directions." },
    ],
  }),
  createPage({
    slug: "hacker-short-usernames",
    title: "Hacker Short Usernames Database",
    seoTitle: "Hacker Short Usernames Database - Short Tech and Glitch Username Ideas",
    description: "Browse short hacker usernames from the NameLaunchpad database with copy buttons, tech-style filters, and compact handle ideas.",
    intro: "This page combines hacker-style naming with short-length intent for users who want compact techy handles that still stay readable.",
    keywords: ["short hacker usernames", "tech usernames", "glitch handles", "hacker database"],
    styles: ["hacker"],
    categories: ["short"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Hacker Usernames", href: "/hacker-usernames", description: "Browse the broader hacker username listing page." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare with more general short username results." },
      { title: "Hacker Username Generator", href: "/generators/hacker-username-generator", description: "Generate more tech-heavy usernames directly." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Compare compact hacker names with cleaner short-name results." },
    ],
  }),
  createPage({
    slug: "gaming-cool-usernames",
    title: "Gaming Cool Usernames Database",
    seoTitle: "Gaming Cool Usernames Database - Cool Gamer Handle Ideas",
    description: "Browse cool gaming usernames from the NameLaunchpad database with copy buttons, gaming filters, and cool handle ideas.",
    intro: "This page narrows the database into cool gaming usernames for users who want flexible gamer handles without drifting into social-only styles.",
    keywords: ["cool gaming usernames", "cool gamer tags", "gaming handle ideas", "gaming database"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Open the broader gaming username database page." },
      { title: "Cool Usernames", href: "/username-database/cool-usernames", description: "Compare with general cool username results." },
      { title: "Cool Username Generator", href: "/generators/cool-username-generator", description: "Generate more cool handle ideas directly." },
      { title: "Cool Usernames for Gamers", href: "/cool-usernames-for-gamers", description: "Read the related SEO page with examples and links." },
    ],
  }),
  createPage({
    slug: "social-aesthetic-usernames",
    title: "Social Aesthetic Usernames Database",
    seoTitle: "Social Aesthetic Usernames Database - Aesthetic Social Handle Ideas",
    description: "Browse aesthetic social usernames from the NameLaunchpad database with copy buttons, style filters, and creator-focused naming pages.",
    intro: "This page narrows the database into aesthetic social usernames for users who care more about profile feel, creator polish, and visual branding.",
    keywords: ["aesthetic social usernames", "social handles", "creator usernames", "aesthetic database"],
    categories: ["social"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Social Usernames", href: "/username-database/social-usernames", description: "Open the broader social username page." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "See the wider aesthetic database page." },
      { title: "Aesthetic Username Generator", href: "/generators/aesthetic-username-generator", description: "Generate more soft and stylish handles." },
      { title: "TikTok Username Ideas", href: "/tiktok-username-ideas", description: "Open a related social SEO page." },
    ],
  }),
  createPage({
    slug: "duo-gaming-usernames",
    title: "Duo Gaming Usernames Database",
    seoTitle: "Duo Gaming Usernames Database - Duo Gamer Name Ideas",
    description: "Browse duo gaming usernames from the NameLaunchpad database with copy buttons, duo filters, and related team naming pages.",
    intro: "This page narrows the username database into duo gaming names for users who want paired identities without jumping all the way to clan naming.",
    keywords: ["duo gaming usernames", "duo gamer tags", "pair usernames", "gaming duo names"],
    categories: ["duo", "gaming"],
    featuredLinks: [
      { title: "Duo Usernames", href: "/username-database/duo-usernames", description: "Open the broader duo username database page." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "See more general gaming name directions." },
      { title: "Duo Gamertag Guide", href: "/duo-gamertag-guide", description: "Open a duo-focused SEO page with more examples." },
      { title: "Clan Name Generator", href: "/clan-name-generator", description: "Move into larger team naming when needed." },
    ],
  }),
  createPage({
    slug: "clan-gaming-usernames",
    title: "Clan Gaming Usernames Database",
    seoTitle: "Clan Gaming Usernames Database - Clan and Team Username Ideas",
    description: "Browse clan gaming usernames from the NameLaunchpad database with copy buttons, team filters, and related clan naming pages.",
    intro: "This page narrows the database into clan-oriented gaming usernames for users who need team-ready names instead of solo handles.",
    keywords: ["clan gaming usernames", "team usernames", "clan handles", "gaming clan names"],
    categories: ["clan", "gaming"],
    featuredLinks: [
      { title: "Clan Usernames", href: "/username-database/clan-usernames", description: "Open the broader clan username database page." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Compare with solo gaming handle directions." },
      { title: "Clan Name Generator", href: "/clan-name-generator", description: "Generate more clan and team names directly." },
      { title: "Clan Name Ideas", href: "/blog/clan-name-ideas", description: "Read the related clan naming article." },
    ],
  }),
  createPage({
    slug: "rare-short-usernames",
    title: "Rare Short Usernames Database",
    seoTitle: "Rare Short Usernames Database - Rare Short Username Ideas",
    description: "Browse rare short usernames from the NameLaunchpad database with copy buttons, compact filters, and related rare-name pages.",
    intro: "This page combines short-length and rarity intent for users who want cleaner premium handles that stay compact and memorable.",
    keywords: ["rare short usernames", "short rare handles", "compact rare usernames", "short username database"],
    categories: ["short", "rare"],
    rarities: ["rare", "epic", "legendary"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Open the broader short-name database page." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Compare with wider rare-name results." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Generate or browse very compact premium handles." },
      { title: "Short Gamer Names", href: "/short-gamer-names", description: "Open the short-name SEO page with more examples." },
    ],
  }),
  createPage({
    slug: "clan-usernames",
    title: "Clan Usernames Database",
    seoTitle: "Clan Usernames Database - Clan, Squad, and Team Username Ideas",
    description: "Browse clan usernames from the NameLaunchpad database with copy buttons, team filters, and related clan naming pages.",
    intro: "This database page focuses on clan usernames for teams that need a stronger group identity than a solo gamertag but less structure than a full clan name list.",
    keywords: ["clan usernames", "team usernames", "squad usernames", "clan handle ideas"],
    categories: ["clan"],
    featuredLinks: [
      { title: "Clan Name Generator", href: "/clan-name-generator", description: "Generate full clan and team names for larger groups." },
      { title: "Clan Name Ideas", href: "/blog/clan-name-ideas", description: "Read a long-form article with clan and squad naming ideas." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Compare team names with broader solo gaming handles." },
      { title: "Duo Usernames", href: "/username-database/duo-usernames", description: "Step down into paired-name ideas when you need a two-player identity." },
    ],
  }),
  createPage({
    slug: "duo-usernames",
    title: "Duo Usernames Database",
    seoTitle: "Duo Usernames Database - Duo Gamer Tag and Pair Username Ideas",
    description: "Browse duo usernames from the NameLaunchpad database with copy buttons, team filters, and related paired naming pages.",
    intro: "This database page narrows the full username system into duo-friendly names for two-player teams, couples, or linked creator profiles.",
    keywords: ["duo usernames", "pair usernames", "duo gamer tags", "matching handles"],
    categories: ["duo"],
    featuredLinks: [
      { title: "Duo Gamertag Guide", href: "/duo-gamertag-guide", description: "Open a dedicated SEO page with paired name examples and tips." },
      { title: "Clan Usernames", href: "/username-database/clan-usernames", description: "Move from paired naming into larger team identity ideas." },
      { title: "Gaming Usernames", href: "/username-database/gaming-usernames", description: "Compare duo names with broader gaming handle options." },
      { title: "Username Generator", href: "/username-generator", description: "Generate more custom paired username directions with keywords and styles." },
    ],
  }),
  createPage({
    slug: "fortnite-usernames",
    title: "Fortnite Usernames Database",
    seoTitle: "Fortnite Usernames Database - Fortnite Username and Gamertag Ideas",
    description: "Browse Fortnite usernames from the NameLaunchpad database with copy buttons, gaming filters, and links to Fortnite naming tools.",
    intro: "This page narrows the database into Fortnite-friendly naming patterns for users who want battle-ready handles, cleaner lobby names, and faster comparison than a broad gaming list.",
    keywords: ["fortnite usernames", "fortnite gamertags", "fortnite name ideas", "fortnite handles"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Fortnite Name Generator", href: "/fortnite-name-generator", description: "Generate more Fortnite-ready names with the dedicated tool." },
      { title: "Best Fortnite Usernames", href: "/blog/best-fortnite-usernames", description: "Read the long-form Fortnite username article with examples." },
      { title: "Cool Usernames", href: "/username-database/cool-usernames", description: "Compare Fortnite names with broader cool handle ideas." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Move into rarer competitive gaming names when needed." },
    ],
  }),
  createPage({
    slug: "fortnite-short-usernames",
    title: "Fortnite Short Usernames Database",
    seoTitle: "Fortnite Short Usernames Database - Short Fortnite Name Ideas",
    description: "Browse short Fortnite usernames from the NameLaunchpad database with copy buttons, short-name filters, and Fortnite naming links.",
    intro: "This page combines Fortnite naming intent with shorter username structure for players who want more compact names that still feel competitive and readable in-game.",
    keywords: ["short fortnite usernames", "fortnite short names", "fortnite gamertags", "short gamer tags"],
    categories: ["gaming", "short"],
    styles: ["cool"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Fortnite Name Generator", href: "/fortnite-name-generator", description: "Generate more short and punchy Fortnite names directly." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare Fortnite-specific results with the broader short-name database." },
      { title: "OG Username Finder", href: "/og-username-finder", description: "Push even further into compact premium-looking names." },
      { title: "Best Fortnite Usernames", href: "/blog/best-fortnite-usernames", description: "Read related Fortnite naming advice and examples." },
    ],
  }),
  createPage({
    slug: "roblox-usernames",
    title: "Roblox Usernames Database",
    seoTitle: "Roblox Usernames Database - Roblox Username Ideas and Handle Examples",
    description: "Browse Roblox usernames from the NameLaunchpad database with copy buttons, gaming filters, and kid-friendly naming links.",
    intro: "This page narrows the database into Roblox-style usernames for users who want playful, readable, and more platform-friendly handle ideas.",
    keywords: ["roblox usernames", "roblox username ideas", "roblox handles", "roblox gamer tags"],
    categories: ["gaming"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Roblox Username Generator", href: "/roblox-username-generator", description: "Generate more Roblox-ready usernames with the dedicated tool." },
      { title: "Cool Roblox Usernames", href: "/blog/cool-roblox-usernames", description: "Read a related article with Roblox naming ideas and tips." },
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "Compare Roblox-friendly names with broader softer username ideas." },
      { title: "Aesthetic Usernames", href: "/username-database/aesthetic-usernames", description: "Open the wider aesthetic naming page for adjacent styles." },
    ],
  }),
  createPage({
    slug: "roblox-cute-usernames",
    title: "Roblox Cute Usernames Database",
    seoTitle: "Roblox Cute Usernames Database - Cute Roblox Username Ideas",
    description: "Browse cute Roblox usernames from the NameLaunchpad database with copy buttons, soft-style filters, and related Roblox naming pages.",
    intro: "This page combines Roblox naming with softer cute and aesthetic directions for users who want more playful, friendly, and profile-ready username ideas.",
    keywords: ["cute roblox usernames", "roblox cute names", "roblox username ideas", "soft gamer names"],
    categories: ["gaming", "cute"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "Roblox Username Generator", href: "/roblox-username-generator", description: "Generate more Roblox-friendly names directly." },
      { title: "Cute Usernames", href: "/username-database/cute-usernames", description: "See the broader cute-name database." },
      { title: "Cool Roblox Usernames", href: "/blog/cool-roblox-usernames", description: "Read the related Roblox article with more examples." },
      { title: "Aesthetic Cute Usernames", href: "/username-database/aesthetic-cute-usernames", description: "Compare Roblox results with broader soft aesthetic names." },
    ],
  }),
  createPage({
    slug: "minecraft-usernames",
    title: "Minecraft Usernames Database",
    seoTitle: "Minecraft Usernames Database - Minecraft Username and Gamertag Ideas",
    description: "Browse Minecraft usernames from the NameLaunchpad database with copy buttons, gaming filters, and links to Minecraft naming pages.",
    intro: "This page narrows the username database into Minecraft-friendly ideas for players who want names that feel creative, adventure-ready, and easy to remember on multiplayer servers.",
    keywords: ["minecraft usernames", "minecraft name ideas", "minecraft gamertags", "minecraft handles"],
    categories: ["gaming"],
    styles: ["fantasy"],
    featuredLinks: [
      { title: "Minecraft Name Generator", href: "/generators/minecraft-name-generator", description: "Generate more Minecraft username ideas with the dedicated page." },
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Compare Minecraft names with broader fantasy directions." },
      { title: "Minecraft Usernames", href: "/blog/minecraft-usernames", description: "Read a related article with Minecraft naming ideas and examples." },
      { title: "Legendary Usernames", href: "/username-database/legendary-usernames", description: "Open more premium-looking fantasy and gaming names." },
    ],
  }),
  createPage({
    slug: "minecraft-short-usernames",
    title: "Minecraft Short Usernames Database",
    seoTitle: "Minecraft Short Usernames Database - Short Minecraft Username Ideas",
    description: "Browse short Minecraft usernames from the NameLaunchpad database with copy buttons, short-name filters, and related Minecraft naming links.",
    intro: "This page combines Minecraft naming intent with shorter structure for users who want compact server-friendly names without losing creative tone.",
    keywords: ["short minecraft usernames", "minecraft short names", "minecraft handle ideas", "short gamer names"],
    categories: ["gaming", "short"],
    styles: ["fantasy"],
    lengths: ["short"],
    featuredLinks: [
      { title: "Minecraft Name Generator", href: "/generators/minecraft-name-generator", description: "Generate more Minecraft names directly." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare with the wider short-name database." },
      { title: "Fantasy Usernames", href: "/username-database/fantasy-usernames", description: "Move into broader fantasy naming patterns." },
      { title: "Short Gamer Names", href: "/short-gamer-names", description: "Open the short-name SEO page with more examples." },
    ],
  }),
  createPage({
    slug: "valorant-usernames",
    title: "Valorant Usernames Database",
    seoTitle: "Valorant Usernames Database - Valorant Username and Tag Ideas",
    description: "Browse Valorant usernames from the NameLaunchpad database with copy buttons, gaming filters, and competitive naming links.",
    intro: "This page narrows the database into Valorant-ready naming patterns for players who want sharper, more competitive handles without browsing unrelated categories.",
    keywords: ["valorant usernames", "valorant name ideas", "valorant handles", "valorant tags"],
    categories: ["gaming"],
    styles: ["dark"],
    featuredLinks: [
      { title: "Valorant Name Generator", href: "/generators/valorant-name-generator", description: "Generate more Valorant-friendly names directly." },
      { title: "Dark Usernames", href: "/username-database/dark-usernames", description: "Compare Valorant naming with broader darker style directions." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Move into rarer competitive gaming names." },
      { title: "Valorant Usernames", href: "/blog/valorant-usernames", description: "Read a related article with Valorant naming advice." },
    ],
  }),
  createPage({
    slug: "valorant-rare-usernames",
    title: "Valorant Rare Usernames Database",
    seoTitle: "Valorant Rare Usernames Database - Rare Valorant Username Ideas",
    description: "Browse rare Valorant usernames from the NameLaunchpad database with copy buttons, rarity filters, and competitive naming links.",
    intro: "This page combines Valorant search intent with rare naming signals for players who want a more premium-looking competitive handle.",
    keywords: ["rare valorant usernames", "valorant rare names", "competitive gamertags", "rare gaming names"],
    categories: ["gaming", "rare"],
    styles: ["dark"],
    rarities: ["rare", "epic", "legendary"],
    featuredLinks: [
      { title: "Valorant Name Generator", href: "/generators/valorant-name-generator", description: "Generate more Valorant names directly." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Compare with the broader rare gaming page." },
      { title: "Dark Rare Usernames", href: "/username-database/dark-rare-usernames", description: "Move into darker rare-name results." },
      { title: "Rare Gamertags", href: "/rare-gamertags", description: "Read the related rare-name SEO page." },
    ],
  }),
  createPage({
    slug: "discord-usernames",
    title: "Discord Usernames Database",
    seoTitle: "Discord Usernames Database - Discord Username and Handle Ideas",
    description: "Browse Discord usernames from the NameLaunchpad database with copy buttons, social filters, and links to Discord naming pages.",
    intro: "This page narrows the database into Discord-style names for users who want cleaner usernames that work across communities, servers, and creator profiles.",
    keywords: ["discord usernames", "discord name ideas", "discord handles", "discord profile names"],
    categories: ["social"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "Discord Username Generator", href: "/generators/discord-username-generator", description: "Generate more Discord-ready names directly." },
      { title: "Discord Username Guide", href: "/discord-username-guide", description: "Open a dedicated SEO page with more Discord username ideas." },
      { title: "Social Usernames", href: "/username-database/social-usernames", description: "Compare with the broader social handle database." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Move into creator-first naming directions." },
    ],
  }),
  createPage({
    slug: "discord-cool-usernames",
    title: "Discord Cool Usernames Database",
    seoTitle: "Discord Cool Usernames Database - Cool Discord Username Ideas",
    description: "Browse cool Discord usernames from the NameLaunchpad database with copy buttons, style filters, and related Discord naming pages.",
    intro: "This page combines Discord intent with cooler naming patterns for users who want a handle that feels cleaner, more modern, and still social-first.",
    keywords: ["cool discord usernames", "discord username ideas", "discord cool names", "discord handles"],
    categories: ["social"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Discord Username Generator", href: "/generators/discord-username-generator", description: "Generate more Discord names with the dedicated generator page." },
      { title: "Cool Usernames", href: "/username-database/cool-usernames", description: "Compare with the wider cool-name database." },
      { title: "Discord Username Guide", href: "/discord-username-guide", description: "Read related Discord naming advice and examples." },
      { title: "Social Aesthetic Usernames", href: "/username-database/social-aesthetic-usernames", description: "Open a softer adjacent social naming page." },
    ],
  }),
  createPage({
    slug: "twitch-usernames",
    title: "Twitch Usernames Database",
    seoTitle: "Twitch Usernames Database - Twitch Username and Stream Name Ideas",
    description: "Browse Twitch usernames from the NameLaunchpad database with copy buttons, creator filters, and links to Twitch naming pages.",
    intro: "This page narrows the database into Twitch-style usernames for streamers who want more discoverable, on-brand, and channel-ready handles.",
    keywords: ["twitch usernames", "twitch name ideas", "stream names", "creator handles"],
    categories: ["social"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "Twitch Username Generator", href: "/generators/twitch-username-generator", description: "Generate more Twitch-ready names directly." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Compare with the broader creator-name database." },
      { title: "Streamer Names", href: "/blog/streamer-names", description: "Read the related creator naming article." },
      { title: "Twitch Streamer Name Guide", href: "/twitch-streamer-name-guide", description: "Open a Twitch-focused SEO page with more examples." },
    ],
  }),
  createPage({
    slug: "twitch-streamer-usernames",
    title: "Twitch Streamer Usernames Database",
    seoTitle: "Twitch Streamer Usernames Database - Streamer-Friendly Twitch Name Ideas",
    description: "Browse Twitch streamer usernames from the NameLaunchpad database with copy buttons, creator filters, and channel branding links.",
    intro: "This page combines Twitch and creator branding intent for users who want names that fit overlays, alerts, clips, and profile discovery more cleanly.",
    keywords: ["twitch streamer usernames", "twitch streamer names", "creator handles", "channel name ideas"],
    categories: ["social"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "Twitch Username Generator", href: "/generators/twitch-username-generator", description: "Generate more Twitch and streamer-friendly names directly." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "See the broader creator-name database." },
      { title: "Streamer Short Usernames", href: "/username-database/streamer-short-usernames", description: "Compare with shorter creator branding ideas." },
      { title: "Twitch Streamer Name Ideas", href: "/twitch-streamer-name-ideas", description: "Open the related Twitch SEO page." },
    ],
  }),
  createPage({
    slug: "apex-usernames",
    title: "Apex Usernames Database",
    seoTitle: "Apex Usernames Database - Apex Name and Gamertag Ideas",
    description: "Browse Apex usernames from the NameLaunchpad database with copy buttons, gaming filters, and battle-focused naming links.",
    intro: "This page narrows the database into Apex-ready handles for players who want sharper battle royale names without searching the full gaming database.",
    keywords: ["apex usernames", "apex gamertags", "apex name ideas", "battle royale usernames"],
    categories: ["gaming"],
    styles: ["dark"],
    featuredLinks: [
      { title: "Apex Name Generator", href: "/generators/apex-name-generator", description: "Generate more Apex-friendly usernames directly." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Compare Apex names with rarer gaming handle options." },
      { title: "Dark Usernames", href: "/username-database/dark-usernames", description: "Open darker adjacent naming patterns for competitive handles." },
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Generate broader cross-platform gamer tag ideas." },
    ],
  }),
  createPage({
    slug: "cod-usernames",
    title: "COD Usernames Database",
    seoTitle: "COD Usernames Database - Call of Duty Username and Tag Ideas",
    description: "Browse COD usernames from the NameLaunchpad database with copy buttons, gaming filters, and tactical naming links.",
    intro: "This page narrows the database into Call of Duty style handles for players who want more tactical, aggressive, and readable multiplayer names.",
    keywords: ["cod usernames", "call of duty names", "cod gamertags", "fps usernames"],
    categories: ["gaming"],
    styles: ["dark"],
    featuredLinks: [
      { title: "COD Name Generator", href: "/generators/cod-name-generator", description: "Generate more Call of Duty naming ideas directly." },
      { title: "Dark Rare Usernames", href: "/username-database/dark-rare-usernames", description: "Compare COD names with rarer dark handle ideas." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Move into broader premium gaming name results." },
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Open the broader gamer tag tool for console and shooter tags." },
    ],
  }),
  createPage({
    slug: "pubg-usernames",
    title: "PUBG Usernames Database",
    seoTitle: "PUBG Usernames Database - PUBG Username and Battleground Name Ideas",
    description: "Browse PUBG usernames from the NameLaunchpad database with copy buttons, gaming filters, and battle royale naming links.",
    intro: "This page narrows the database into PUBG-friendly names for players who want battleground-ready usernames with cleaner competitive tone.",
    keywords: ["pubg usernames", "pubg names", "battle royale usernames", "pubg gamertags"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "PUBG Name Generator", href: "/generators/pubg-name-generator", description: "Generate more PUBG-ready handles directly." },
      { title: "Fortnite Usernames", href: "/username-database/fortnite-usernames", description: "Compare PUBG names with another battle royale naming cluster." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Open rarer competitive gaming names." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Move into shorter battleground-ready handle options." },
    ],
  }),
  createPage({
    slug: "steam-usernames",
    title: "Steam Usernames Database",
    seoTitle: "Steam Usernames Database - Steam Username and Gamertag Ideas",
    description: "Browse Steam usernames from the NameLaunchpad database with copy buttons, gaming filters, and PC naming links.",
    intro: "This page narrows the database into Steam-friendly usernames for PC players who want cleaner profile handles across multiplayer libraries and communities.",
    keywords: ["steam usernames", "steam name ideas", "pc gamertags", "steam profile names"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Steam Gamertag Generator", href: "/generators/steam-gamertag-generator", description: "Generate more Steam and PC-friendly handles directly." },
      { title: "Cool Usernames", href: "/username-database/cool-usernames", description: "Compare Steam names with broader clean handle ideas." },
      { title: "Rare Usernames", href: "/username-database/rare-usernames", description: "Move into rarer name results for cleaner profile branding." },
      { title: "Username Generator", href: "/username-generator", description: "Generate more custom usernames with style and length filters." },
    ],
  }),
  createPage({
    slug: "xbox-gamertag-usernames",
    title: "Xbox Gamertag Usernames Database",
    seoTitle: "Xbox Gamertag Usernames Database - Xbox Name and Gamertag Ideas",
    description: "Browse Xbox gamertag usernames from the NameLaunchpad database with copy buttons, gaming filters, and console naming links.",
    intro: "This page narrows the database into Xbox-style gamertag ideas for console players who want names that stay readable across multiplayer profiles and lobbies.",
    keywords: ["xbox gamertags", "xbox usernames", "xbox name ideas", "console gamer tags"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Xbox Gamertag Generator", href: "/generators/xbox-gamertag-generator", description: "Generate more Xbox-ready gamertag ideas directly." },
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Open the broader cross-platform gamer tag tool." },
      { title: "Short Usernames", href: "/username-database/short-usernames", description: "Compare Xbox tags with shorter clean handle options." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Move into premium-looking competitive names." },
    ],
  }),
  createPage({
    slug: "psn-usernames",
    title: "PSN Usernames Database",
    seoTitle: "PSN Usernames Database - PlayStation Username and Online ID Ideas",
    description: "Browse PSN usernames from the NameLaunchpad database with copy buttons, gaming filters, and console naming links.",
    intro: "This page narrows the database into PlayStation-friendly usernames for players who want cleaner online ID directions without scanning the full gaming set.",
    keywords: ["psn usernames", "playstation names", "online id ideas", "console usernames"],
    categories: ["gaming"],
    styles: ["cool"],
    featuredLinks: [
      { title: "Gamer Tag Generator", href: "/gamer-tag-generator", description: "Generate broader console and cross-platform gamer tag ideas." },
      { title: "Xbox Gamertag Usernames", href: "/username-database/xbox-gamertag-usernames", description: "Compare PlayStation naming with the Xbox naming cluster." },
      { title: "Steam Usernames", href: "/username-database/steam-usernames", description: "Move into PC profile naming if you want a broader platform view." },
      { title: "Rare Gaming Usernames", href: "/username-database/rare-gaming-usernames", description: "Open rarer gaming handles for cleaner console branding." },
    ],
  }),
  createPage({
    slug: "youtube-usernames",
    title: "YouTube Usernames Database",
    seoTitle: "YouTube Usernames Database - YouTube Gaming and Channel Name Ideas",
    description: "Browse YouTube usernames from the NameLaunchpad database with copy buttons, creator filters, and channel naming links.",
    intro: "This page narrows the database into YouTube-friendly names for users who want creator handles that read well in channel headers, thumbnails, and clips.",
    keywords: ["youtube usernames", "youtube channel names", "gaming channel names", "creator usernames"],
    categories: ["social"],
    styles: ["streamer"],
    featuredLinks: [
      { title: "YouTube Username Generator", href: "/generators/youtube-username-generator", description: "Generate more YouTube-friendly usernames directly." },
      { title: "Streamer Usernames", href: "/username-database/streamer-usernames", description: "Compare with the broader creator-name database." },
      { title: "Twitch Usernames", href: "/username-database/twitch-usernames", description: "Compare YouTube naming with Twitch-first channel handles." },
      { title: "Username Generator", href: "/username-generator", description: "Generate more creator handles with custom keywords and styles." },
    ],
  }),
  createPage({
    slug: "tiktok-usernames",
    title: "TikTok Usernames Database",
    seoTitle: "TikTok Usernames Database - TikTok Username and Handle Ideas",
    description: "Browse TikTok usernames from the NameLaunchpad database with copy buttons, social filters, and creator naming links.",
    intro: "This page narrows the database into TikTok-style usernames for users who want shorter, catchier handles that fit trend-driven creator branding.",
    keywords: ["tiktok usernames", "tiktok handles", "creator names", "social username ideas"],
    categories: ["social"],
    styles: ["aesthetic"],
    featuredLinks: [
      { title: "TikTok Username Generator", href: "/generators/tiktok-username-generator", description: "Generate more TikTok-ready names directly." },
      { title: "Social Aesthetic Usernames", href: "/username-database/social-aesthetic-usernames", description: "Compare TikTok names with broader soft social handle ideas." },
      { title: "Social Usernames", href: "/username-database/social-usernames", description: "Browse the wider social-username database." },
      { title: "Search Generators", href: "/search?q=tiktok", description: "Search for more TikTok and creator naming pages instantly." },
    ],
  }),
];

export const usernameDatabasePageSlugs = usernameDatabasePages.map((page) => page.slug);

export function getUsernameDatabasePage(slug: string) {
  return usernameDatabasePages.find((page) => page.slug === slug);
}
